apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-web
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eshop-web
  template:
    metadata:
      labels:
        app: eshop-web
    spec:
      containers:
        - name: eshop-web
          image: adarshjain428/eshopwebmvc:v1
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ConnectionStrings__CatalogConnection
              value: >
                Server=$(DB_HOST),1433;
                Database=$(DB_NAME);
                User Id=$(DB_USER);
                Password=$(DB_PASSWORD);
                TrustServerCertificate=True;

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: eshop-db-config
                  key: DB_HOST

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: eshop-db-config
                  key: DB_NAME

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: eshop-db
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eshop-db
                  key: DB_PASSWORD


---
apiVersion: v1
kind: Service
metadata:
  name: eshop-web
  namespace: dev
spec:
  selector:
    app: eshop-web
  ports:
    - port: 80
      targetPort: 8080
